### ISSUE TITLE
Running the server? Missing part in the doc?

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#11]
HI. We are in the process of installing IRES on a new cluster. I managed to build everything and made the required updates to the configuration files (BTW, a simpler build process would make the tool more attractive).

The next step is to run the 'HelloWorld' application. Nothing is said about running the IReS server, which seems to be a condition to access the IReS UI. Can you please provide the complement to the install doc? Thx.

**Comment by gsvic** [comment]
Hello,
The documentation contains instructions about how to start the server which can be found in [this link](http://cognito.cslab.ece.ntua.gr/ires_docs/install.html#start-the-ires-server).

**Comment by Stan-imr** [comment]
Cool, thanks. But we use the doc taken from the gh-pages branch, and yours seems much more up-to-date. Is there a way to get the latest doc from github, or at least to know where the official ASAP doc is? This would save us some time.

**Comment by gsvic** [comment]
Sure. The official documentation source code can be found in this repository in the ires_docs folder in the project's parent folder. However, you can use the aforementioned documentation [link](http://cognito.cslab.ece.ntua.gr/ires_docs/) which is always up to date. Every modification in the documentation is always being synced with the one in this link.

**Comment by Stan-imr** [comment]
Good to know. Thx.

There is an ASAP-documentation repo, the doc should be eventually sync with that one as well.  We'll use your link for the time being.

**Comment by gsvic** [comment]
Thanks for mentioning it. Currently, I see that I am not a collaborator in this repo and thus I cannot commit anything. Who can give me access to this?

**Comment by Stan-imr** [comment]
You can coordinate with Maria Chalkiadaki, mhalkiad@ics.forth.gr. Keep me updated, I think that Philippe Rigaux made some cosmetic changes to the IRES installation doc to reflect some comments that we had.
