### ISSUE TITLE
Hardcoded paths in install scripts?

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#12]
Hello

As we try to run the IReS server, we run into troubles. It seems that some paths are still hardcoded in the scripts. For instance, in asap-server:

#IRES_HOME=path/to/IReS-Platform_project
IRES_HOME="/Users/npapa/Documents/workspaceASAP/IReS-Platform"

Also, for the YARN_CLASSPATH

YARN_CLASSPATH="/home/bill/PhD/projects/yarn/etc/hadoop:/home/bill/PhD/projects/yarn/share/hadoop/common/lib/*:/home/bill/PhD/projects/yarn/share/hadoop/common/*:/home/bill/PhD/projects/yarn/share/hadoop/hdfs:/home/bill/PhD/projects/yarn/share/hadoop/hdfs/lib/*:/home/bill/PhD/projects/yarn/share/hadoop/hdfs/*:/home/bill/PhD/projects/yarn/share/hadoop/yarn/lib/*:/home/bill/PhD/projects/yarn/share/hadoop/yarn/*:/home/bill/PhD/projects/yarn/share/hadoop/mapreduce/lib/*:/home/bill/PhD/projects/yarn/share/hadoop/mapreduce/*:/contrib/capacity-scheduler/*.jar"
CLASSPATH=$CLASSPATH:$YARN_CLASSPATH

I don't think that we are supposed to edit that manually.

Finally, the ASAP documentation repo  is still not in line with http://cognito.cslab.ece.ntua.gr/ires_docs/install.html#start-the-ires-server

Thanks for your help

**Comment by gsvic** [comment]
Hello,

If you install the project by using the installation script (http://cognito.cslab.ece.ntua.gr/ires_docs/install.html) the IRES_HOME will be set automatically. 

Also, during the installation the user is prompted to enter the YARN_CLASSPATH.

I have just updated the documentation repo https://github.com/project-asap/ASAP-documentation.

**Comment by Stan-imr** [comment]
Allright, yet it will be cleaner to remove all the references to local environments in the next versions.
