### ISSUE TITLE
Starting/stopping the server

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#13]
We try to start the IRES server:

./install.sh -r start
start-ing ASAP server
Error: Could not find or load main class gr.ntua.cslab.asap.daemon.Main

Starting again:

start-ing ASAP server
ASAP Server already running (14908)

Stopping:
IReS-Platform/asap-platform/asap-server/src/main/scripts/asap-server: line 32: kill: (14908) - No such process

Maybe related to harcoded paths?

Thanks for helping

S.

**Comment by gsvic** [comment]
Indeed, this is caused because the environmental variables are wrongly set. Check out this https://github.com/project-asap/IReS-Platform/issues/12#issuecomment-268522021.

**Comment by Stan-imr** [comment]
OK, we tried with the last version, and it works. Let's proceed. Thanks a alot.
