### ISSUE TITLE
Starting IReS

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#15]
Hello guys,

I would be safer to provide a script "start-ires.sh" and "stop-ires.sh" rather that the "install.sh" file with running options. There is a risk to rebuild again and again IRES if we mistype something.

Stan

**Comment by vpapaioannou** [comment]
Taking your good proposal one step further, it would be very good to have a similar to YARN and Spark "sbin" folder for IReS as it seems to be a standard practice. What about of having implemented it by you?

**Comment by Stan-imr** [comment]
Sure, but not now, as we are busy setting up our experiments.

**Comment by gsvic** [comment]
The `sbin` folder with the corresponding `ires.sh` script has been added https://github.com/project-asap/IReS-Platform/commit/4839d226f57effc14901a07dcd1f77f865b4a02a.
