### ISSUE TITLE
Using ElasticSearch as input

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#16]
Our dataset is available in an ElasticSearch server. Looking at the Dataset Metadata description, it is not clear how we define this server as an input. Do we have to write some kind of wrapper? 

Also, is there any example somewhere of a Java module that can be used as an operator implementation in IReS? We have a set of java functions that can be connected to create a workflow, but it is unclear how we can pug them in IReS.

Thanks

Stan

**Comment by vpapaioannou** [comment]
See [this](https://github.com/project-asap/IReS-Platform/blob/master/asap-platform/asap-server/asapLibrary/datasets/tfidf_scikit0.02) to have a taste of reading from HDFS and [this](https://github.com/project-asap/IReS-Platform/blob/master/asap-platform/asap-server/asapLibrary/datasets/customers) of reading from a database or similar.
