### ISSUE TITLE
What is an IRES Operator?

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#17]
Hello,

Would it be possible to obtain a precise definition of what an IRES operator is? Looking at the doc pieces, it seems that it is a process that takes as input HDFS files and produces HDFS files as output. Is that correct (seems quite restricted)? Is there a way to stream data from one operator to another, instead of materialization? Is there a way to use data stores as input/output sources ?

Thx

Stan

**Comment by vpapaioannou** [comment]
Hello Stan,

roughly speaking,

1. the input and the output of an IReS operator can be whatever you want like a local flat file, a database or anything else you can think of.
2. an IReS operator on a logical level is a black box unit of execution. On IReS level, this unit includes the execution script and the resources needed for execution. The resources can be split into two categories. The first has to do with the user provided parameters or arguments such as other files as input in order for the execution script to run correctly. This kind of resources are irrelevant to IReS. The second category of resources refers to configuration files and they are required in order for an operator to run in IReS. These configuration files are the .lua file and the metadata file of the operator. The metadata file describes the operator to IReS while the .lua file contains
a. information about the user defined resources( files) mentioned above,
b. information about the resources the operator needs to be executed like cpus, memory, the cluster node of execution. These execution resources are provided by YARN in the form of containers during execution.

Again, the description above is a rough description of an operator.

Kind regards,

Vassilis

**Comment by Stan-imr** [comment]
Thanks a lot. Did I miss a document where a not-so-rough description would be available? 

So, to be specific
  - can we define a dataset at an abstract level, and specify at an implementation 
     level that the dataset  is an ElasticSearch server, or HBase, or HDFS? That would be pretty 
    cool, of course an example would be welcome

  - the "script" notion implies that an operator is sth that is executed as a Yarn container, it can
    be a MR job, a Spark job, a Flink job,  etc.  The next question is: how do we pass intermediate 
   results from one "operator" to the other? Is it always a dataset? Can it be, at a physical level, 
   a memory structure?

A forum would be more appropriate for this kind of question, but since the doc is pretty sparse now, I try to get some info from the source at hand. Thanks in advance.

S.

**Comment by vpapaioannou** [comment]
Again, roughly speaking,

1. With the exception of the very first datasets of the workflow that must be materialized, all others can be abstract. The abstract datasets get materialized upon the workflow materialization and according to operator metadata. Going [here](https://github.com/project-asap/IReS-Platform/tree/master/asap-platform/asap-server/asapLibrary/operators) you will find a plenty of operators. For example, InnerSQL*operators correspond to the different input sources that could be in your case an ElasticSearch server or HBase. In general, for every different input/output source, you need to define corresponding operator accepting such an input/output.

2. The notion of a workflow in most cases implies that each operator knows a priori where to find its inputs and where to write its outputs. An operator A writes in file X( output) and another operator B reads file X( input) and writes file Y. A third operator C reads file Y and produces the final workflow output. Files X,Y must have a statically known location but they should not necessarily exist before execution. During execution however, they must also exist when they needed. This is how intermediate results get populated and they are always datasets. Datasets currently do not have streaming capabilities if this is what you mean. By the way, there is no direct connection between operators but only via a dataset.

**Comment by Stan-imr** [comment]
OK, let's look at that. Thanks a lot for the info.

**Comment by Stan-imr** [comment]
OK, so I seem to understand that we cannot define an abstract dataset that can be used as input of an abstract workflow. In our use case we have as a first operator a scrapper that extracts structured content from web pages. It would have been cool to declare that this operator takes as input an abstract dataset of web pages, and to materialize the dataset either with HDFS, Elastic Search or even local files.

Is it correct? It would make sense to consider that an abstract workflow is completely abstract. Anything that prevents such a design?
