### ISSUE TITLE
Abstract operator disappears after restarting IReS

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#20]
Hi,

We defined an operator, added it to IReS thanks to the UI, and tired to create a workflow (without success, see other issues).

Turns out that when we restart IReS, the operator does not longer appear in the UI. We have to add it again.

**Comment by gsvic** [comment]
Fixed, check out this commit https://github.com/project-asap/IReS-Platform/commit/2341750d757ed7b3ba7bbcd10a80adb31bdf30ca.

Let me know if you face further issues with that.
