### ISSUE TITLE
Role of Constraint.Engine in description files?

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/IReS-Platform#22]
We find in the description file of operators this spec:

Constraints.Engine=Spark

But the executable is a bash script. We'd like to run a Flink job as part of the alternatives for materialized operators in the workflow. Unclear how we can specify this (unless everything is encapsulated in the executable?). Would be nice to have some explanations/examples on the multi-engine aspect. 

Stan

**Comment by gsvic** [comment]
This constraint defines the engine that the operator runs. In the phase of planning, before adding an operator in the materialized workflow IReS checks if the engine is up and running in

http://ires_host:1323/web/clusterStatus

Currently, the engines are hardcoded but we will fix this soon. We will add functionality for the user to be able to add a new engine in a configuration file inside the IReS installation folder.

Currently, there is a quick solution of modifying the engines with the REST API. You can add a new engine with your browser by sending the following REST call

http://ires_host:1323/web/clusterStatus/services/alive/ENGINE_NAME

You will see the new engine in http://ires_host:1323/web/clusterStatus and everything will work fine. Keep in mind that by doing this the engines are kept in main memory. In case the server restart, the new engines will be lost.
