### ISSUE TITLE
After server restart the abstract workflows uploaded using the REST API disappear

### ISSUE THREAD

**Issue by project-asap** [project-asap/IReS-Platform#5]
I upload a new abstract workflow using:
$ curl http://localhost:1323/abstractWorkflows/add/just_testing -H "Content-Type: application/json" --data @/tmp/workflow.json -v
*   Trying ::1...
* Connected to localhost (::1) port 1323 (#0)
> POST /abstractWorkflows/add/just_testing HTTP/1.1
> Host: localhost:1323
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 835
> 
* upload completely sent off: 835 out of 835 bytes
< HTTP/1.1 204 No Content
< Date: Mon, 07 Nov 2016 10:22:03 GMT
< Server: Jetty(9.2.7.v20150116)
< 
* Connection #0 to host localhost left intact

Then, I can see the specific workflow under the Abstract Workflows tab in the Web UI
and moreover I can get request its description using the REST API:
$ curl http://localhost:1323/abstractWorkflows/just_testing -v
*   Trying ::1...
* Connected to localhost (::1) port 1323 (#0)
> GET /abstractWorkflows/just_testing HTTP/1.1
> Host: localhost:1323
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 07 Nov 2016 10:22:26 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Server: Jetty(9.2.7.v20150116)
< 
* Connection #0 to host localhost left intact
{"operators":[{"name":"hdfs_file","cost":"0.0","execTime":"0.0","status":"stopped","isOperator":"false","isAbstract":"false","description":"Constraints.Engine.FS = HDFS<br>Execution.path = hdfs:///user/bill/amazon_data<br>Optimization.size = 932E06<br>","abstractName":"","isTarget":false,"input":[],"output":["HelloWorld"]},{"name":"d1","cost":"0.0","execTime":"0.0","status":"stopped","isOperator":"false","isAbstract":"true","description":"","abstractName":"","isTarget":true,"input":[],"output":[]},{"name":"HelloWorld","cost":"0.0","execTime":"0.0","status":"stopped","isOperator":"true","isAbstract":"true","description":"Constraints.Input.number = 1<br>Constraints.OpSpecification.Algorithm.name = HelloWorld<br>Constraints.Output.number = 1<br>","abstractName":"","isTarget":false,"input":["hdfs_file"],"output":[]}],"name":""}

Then, I restart the server:
./install.sh -r restart

After the restart, the workflow no more appears in the Web UI
and the request for its description fails with 500 ERROR Status:
$  curl http://localhost:1323/abstractWorkflows/just_testing -v 
*   Trying ::1...
* Connected to localhost (::1) port 1323 (#0)
> GET /abstractWorkflows/just_testing HTTP/1.1
> Host: localhost:1323
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 500 Server Error
< Date: Mon, 07 Nov 2016 10:22:54 GMT
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 329
< Connection: close
< Server: Jetty(9.2.7.v20150116)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /abstractWorkflows/just_testing. Reason:
<pre>    java.lang.NullPointerException</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
* Closing connection 0

The exception traceback is the following:
[NullPointerException.txt](https://github.com/project-asap/IReS-Platform/files/575095/NullPointerException.txt)

**Comment by gsvic** [comment]
Fixed: https://github.com/project-asap/IReS-Platform/commit/34e4823f49182796c195ad71741e9121896e67c5
