### ISSUE TITLE
IReS Documentation - clarification

### ISSUE THREAD

**Issue by hvdieren** [project-asap/IReS-Platform#6]
The documentation on creating an operator on IReS does not explain how the script is found. The exampe in ires_docs/build/html/install.html#create-an-input-process-output-workflow creates a count_lines.sh script, but the script is not explicitly mentioned in the description files. It would help users if it was explained how the script is identified.

**Comment by gsvic** [comment]
An extra line describing it has been added in the description file. http://cognito.cslab.ece.ntua.gr/ires_docs/install.html#create-an-input-process-output-workflow
