### ISSUE TITLE
The Web UI permits the creation of an abstract workflow via the Abstract Workflows tab without providing a name

### ISSUE THREAD

**Issue by project-asap** [project-asap/IReS-Platform#7]
After the creation the user is navigated in the specific's workflow view:
http://asap-master:1323/web/abstractWorkflows/newWorkflow?workflowName=
but all the subsequent actions fail because the workflow name is missing
e.g. http://asap-master:1323/web/abstractWorkflows/addRemove?name=Wind_Kmeans&type=1&workflowName=&addRemove=Add+nodes
Moreover, if the user navigates back in the Abstract Workflows view
the workflow appears in the list with the available workflows but is no more accessible
because the hyperlink has no text (and points to /web/abstractWorkflows/):
<ul>
<li><a href="/web/abstractWorkflows/"></a></li><li><a href="/web/abstractWorkflows/hello_world">hello_world</a></li><li><a href="/web/abstractWorkflows/just-testing">just-testing</a></li><li><a href="/web/abstractWorkflows/sociometer">sociometer</a></li><li><a href="/web/abstractWorkflows/statistics">statistics</a></li></ul>

**Comment by gsvic** [comment]
Fixed: https://github.com/project-asap/IReS-Platform/commit/a239eea64bf75b94456739a1ca1d3e378ef4ebf5
