### ISSUE TITLE
Change workflow graph issue

### ISSUE THREAD

**Issue by project-asap** [project-asap/IReS-Platform#8]
Assuming there are 2 abstract operators _Wind_User_Profiling_ & _Wind_User_Profiling_,
a materialized dataset _cdr-2016-01-01_ and an abstract dataset _ff_
If in the respective text area we provide:

```
cdr-2016-01-01,Wind_User_Profiling
Wind_User_Profiling,Wind_Kmeans
Wind_Kmeans,ff
ff,$$target
```

and press Change graph.
The graph appears correctly but the text inside the text area has changed to:
```
cdr-2016-01-01,Wind_User_Profiling,0
Wind_User_Profiling,Wind_Kmeans,0
Wind_User_Profiling,Wind_Kmeans,0
Wind_Kmeans,ff,0
ff,$$target
```
The request URI send is the following:
`http://asap-master:1323/web/abstractWorkflows/changeGraph?workflowName=just-testing-2&workflowGraph=cdr-2016-01-01%2CWind_User_Profiling%0D%0AWind_User_Profiling%2CWind_Kmeans%0D%0AWind_Kmeans%2Cff%0D%0Aff%2C%24%24target`

and the respective unquoted URI is:
```
In [2]: urllib.unquote('http://asap-master:1323/web/abstractWorkflows/changeGraph?workflowName=just-testing-2&workflowGraph=cdr-2016-01-01%2CWind_User_Profiling%0D%0AWind_User_Profiling%2CWind_Kmeans%0D%0AWind_Kmeans%2Cff%0D%0Aff%2C%24%24target')
Out[2]: 'http://asap-master:1323/web/abstractWorkflows/changeGraph?workflowName=just-testing-2&workflowGraph=cdr-2016-01-01,Wind_User_Profiling\r\nWind_User_Profiling,Wind_Kmeans\r\nWind_Kmeans,ff\r\nff,$$target'
```

Moreover,
if we try to fix it by removing everything from the text area and passing again the above input
inside the text area appears:

```
cdr-2016-01-01,Wind_User_Profiling,0
Wind_User_Profiling,Wind_Kmeans,0
Wind_User_Profiling,Wind_Kmeans,1
Wind_User_Profiling,Wind_Kmeans,0
Wind_Kmeans,ff,0
Wind_Kmeans,ff,1
ff,$$target
```

The request URI send is again the following:
`http://asap-master:1323/web/abstractWorkflows/changeGraph?workflowName=just-testing-2&workflowGraph=cdr-2016-01-01%2CWind_User_Profiling%0D%0AWind_User_Profiling%2CWind_Kmeans%0D%0AWind_Kmeans%2Cff%0D%0Aff%2C%24%24target`

**Comment by project-asap** [comment]
In addition to this,
we create an abstract workflow using the respective API call:

` curl http://asap-master:1323/abstractWorkflows/add/sociometer -H "Content-Type: application/json" --data @/tmp/sociometer.json -v`

by passing the following json:

```
{u'name': u'sociometer',
 u'operators': [{u'abstractName': u'',
   u'cost': u'0.0',
   u'description': u'Constraints.Engine.FS=HDFS\nExecution.path=hdfs:///dataset_simulated/2016/synth_data2016-01-01.csv',
   u'execTime': u'0.0',
   u'input': [],
   u'isAbstract': False,
   u'isOperator': False,
   u'isTarget': False,
   u'name': u'cdr-2016-01-01',
   u'output': [u'Wind_User_Profiling'],
   u'status': u'stopped'},
  {u'abstractName': u'',
   u'cost': u'0.0',
   u'description': u'Constraints.Input.number=1,Constraints.OpSpecification.Algorithm.name=user_profiling',
   u'execTime': u'0.0',
   u'input': [u'cdr-2016-01-01'],
   u'isAbstract': True,
   u'isOperator': True,
   u'isTarget': False,
   u'name': u'Wind_User_Profiling',
   u'output': [u'Wind_Kmeans'],
   u'status': u'stopped'},
  {u'abstractName': u'',
   u'cost': u'0.0',
   u'description': u'Constraints.Input.number=1,Constraints.OpSpecification.Algorithm.name=kmeans',
   u'execTime': u'0.0',
   u'input': [u'Wind_User_Profiling'],
   u'isAbstract': True,
   u'isOperator': True,
   u'isTarget': False,
   u'name': u'Wind_Kmeans',
   u'output': [u'final'],
   u'status': u'stopped'},
  {u'abstractName': u'',
   u'cost': u'0.0',
   u'description': u'',
   u'execTime': u'0.0',
   u'input': [u'Wind_Kmeans'],
   u'isAbstract': True,
   u'isOperator': False,
   u'isTarget': True,
   u'name': u'final',
   u'output': [],
   u'status': u'stopped'}]}
```

The workflow appears in the IReS UI but the graph in the text area is:
```
cdr-2016-01-01,Wind_User_Profiling,0
Wind_User_Profiling,Wind_Kmeans,0
Wind_User_Profiling,Wind_Kmeans,1
Wind_User_Profiling,Wind_Kmeans,0
Wind_User_Profiling,Wind_Kmeans,1
Wind_Kmeans,final,0
final,$$target
```

**Comment by npapa** [comment]
The change graph method had a bug and failed to remove the edges that existed in the previous description of the workflow. The bug is fixed now. The numbers appearing at the end of each line represent the position of the edge in the input or output of operators. For example an operator "test" with two inputs "in0" and "in1" and 2 outputs "o0" and "o1" will have the following description:

in0,test,0
in1,test,1 
test,o0,0
test,o1,1

This will also be updated in the documentation.
